package HPEOneView::Models::Servers::ServerProfileTemplates;


use strict;
use warnings;

require Exporter;

our @ISA = qw(Exporter);
our @EXPORT_OK = qw($json_create_spt);
our @EXPORT = qw($json_create_spt);

our $json_create_spt = <<'END_JSON';
{
  "type": "ServerProfileTemplateV2",
  "serverProfileDescription": "",
  "serverHardwareTypeUri": "/rest/server-hardware-types/{server-hardware-types-uuid}",
  "enclosureGroupUri": "/rest/enclosure-groups/{enclosure-groups-uuid}",
  "serialNumberType": "Virtual",
  "macType": "Virtual",
  "wwnType": "Virtual",
  "name": "test",
  "description": "",
  "affinity": "Bay",
  "connections": [
    {
      "id": 1,
      "name": "INTERNAL",
      "functionType": "Ethernet",
      "portId": "Auto",
      "requestedMbps": "2500",
      "networkUri": "/rest/ethernet-networks/{network-uuid}"
    }
  ],
  "boot": {
    "manageBoot": false
  },
  "bootMode": null,
  "firmware": {
    "manageFirmware": false,
    "firmwareBaselineUri": "",
    "forceInstallFirmware": false,
    "firmwareInstallType": null
  },
  "bios": {
    "manageBios": false,
    "overriddenSettings": []
  },
  "hideUnusedFlexNics": true,
  "iscsiInitiatorNameType": "AutoGenerated",
  "localStorage": {
    "sasLogicalJBODs": [],
    "controllers": []
  },
  "sanStorage": null
}
END_JSON
