#！ perl -w

use strict;
use Data::Dumper;
use HPEOneView::Clients::BaseClient;
use HPEOneView::Clients::Settings::Version;
use HPEOneView::Clients::Settings::Appliance;
use HPEOneView::Clients::Security::LoginSessions;
use HPEOneView::Clients::Servers::ServerProfileTemplates;

use HPEOneView::Behaviors::Servers::ServerProfileTemplates;
use HPEOneView::Behaviors::Activity::Tasks;

my $hostname = '';
my $username = '';
my $password = '';
# Set this to directory server name if use directory authorization
#my $login_domain = '';


my $login = HPEOneView::Clients::Security::LoginSessions->new(hostname=>$hostname,userName=>$username,password=>$password);
my $sv = HPEOneView::Behaviors::Servers::ServerProfileTemplates->new(session=>$login->session);


open(my $fh, '>', 'failed_to_create_spt');
foreach my $id (1..640) {
    my $name = "spt-scale-$id";
    my $body = qq({"type":"ServerProfileTemplateV2","serverProfileDescription":"","serverHardwareTypeUri":"/rest/server-hardware-types/uuid","enclosureGroupUri":"/rest/enclosure-groups/uuid","serialNumberType":"Virtual","macType":"Virtual","wwnType":"Virtual","name":"$name","description":"","affinity":"Bay","connections":[{"id":1,"name":"INTERNAL","functionType":"Ethernet","portId":"Auto","requestedMbps":"2500","networkUri":"/rest/ethernet-networks/uuid"}],"boot":{"manageBoot":false},"bootMode":null,"firmware":{"manageFirmware":false,"firmwareBaselineUri":"","forceInstallFirmware":false,"firmwareInstallType":null},"bios":{"manageBios":false,"overriddenSettings":[]},"hideUnusedFlexNics":true,"iscsiInitiatorNameType":"AutoGenerated","localStorage":{"sasLogicalJBODs":[],"controllers":[]},"sanStorage":null});

    if (! $sv->create_spt($body)) {
        print $fh "$name $body\n";
    }
}
close $fh;
